os: unstable

environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  matrix:
    - platform: x86
      fast_finish: true
      generator: "Ninja"
      builder: cygwin
             
    - platform: x64
      fast_finish: true
      generator: "Ninja"
      builder: cygwin 


branches:
  only:
    - master
    - release     

install:
  - if "%platform%"=="x86"  ( C:\cygwin\setup-x86.exe      -qnNdO -R C:/cygwin   -s http://cygwin.mirror.constant.com -l C:/cygwin/var/cache/setup   -P openssl-devel -P libiodbc-devel -P libiodbc2 -P odbc-mysql -P odbc-pgsql -P odbc-sqlite3 -P libmysqlclient-devel -P libsqlite3-devel -P libcrypt-devel -P zip)
  - if "%platform%"=="x86"  ( set "PATH=C:\cygwin\bin;%PATH%"   ; set "TRAVIS_OS_NAME=Win32" )
  - if "%platform%"=="x64"  ( C:\cygwin64\setup-x86_64.exe -qnNdO -R C:/cygwin64 -s http://cygwin.mirror.constant.com -l C:/cygwin64/var/cache/setup -P openssl-devel -P libiodbc-devel -P libiodbc2 -P odbc-mysql -P odbc-pgsql -P odbc-sqlite3 -P libmysqlclient-devel -P libsqlite3-devel -P libcrypt-devel -P zip)
  - if "%platform%"=="x64"  ( set "PATH=C:\cygwin64\bin;%PATH%" ; set "TRAVIS_OS_NAME=Win64" )
#  - if "%platform%"=="x86" ( choco install -r -y mingw --x86 )
#  - if "%platform%"=="x64" ( choco install -r -y mingw )
  - choco install -r -y ninja


build_script:
  - cmd: echo Running cmake ...
  - cmd: mkdir build

  # Build the 32bit executable
  - if "%platform%"=="x86" ( move CMakeLists.txt      CMakeLists.x64.txt )
  - if "%platform%"=="x86" ( copy CMakeLists.x86.txt  .\CMakeLists.txt )
  - if "%platform%"=="x86" ( cd build )
  - if "%platform%"=="x86" ( copy C:\cygwin\bin\gcc.exe C:\cygwin\bin\cc.exe )
  
  # Build the 64bit executable
  - if "%platform%"=="x64" ( cd build )
  - if "%platform%"=="x64" ( copy C:\cygwin64\bin\gcc.exe C:\cygwin64\bin\cc.exe )

  - cmake -G "Ninja" ..
  - ninja
  # Test running the binary
  - .\NFsim.exe
  - "mkdir NFsim-Win%platform%"
  - "cp NFsim.exe  NFsim-Win%platform%"

  - if "%platform%"=="x86" "cp C:\cygwin\bin\cygwin*dll NFsim-Win%platform%"
  - if "%platform%"=="x86" "cp C:\cygwin\bin\cygstdc*dll NFsim-Win%platform%"
  - if "%platform%"=="x86" "cp C:\cygwin\bin\cygz*dll NFsim-Win%platform%"
  - if "%platform%"=="x86" "cp C:\cygwin\bin\cyggcc*dll NFsim-Win%platform%"

  - if "%platform%"=="x64" "cp C:\cygwin64\bin\cygwin*dll NFsim-Win%platform%"
  - if "%platform%"=="x64" "cp C:\cygwin64\bin\cygstdc*dll NFsim-Win%platform%"
  - if "%platform%"=="x64" "cp C:\cygwin64\bin\cygz*dll NFsim-Win%platform%"
  - if "%platform%"=="x64" "cp C:\cygwin64\bin\cyggcc*dll NFsim-Win%platform%"

  - "7z a NFsim-Win%platform%.zip NFsim-Win%platform%"
  - cd ..

artifacts:
  - path: '.\build\NFsim-*.zip'
    name: nfsim
    type: zip

deploy:
  - provider: BinTray
    username: jczech
    subject: jczech
    api_key:
      # api key from https://bintray.com/profile/edit
      # encrypted in https://ci.appveyor.com/tools/encrypt
      secure: XzrXGPWsRRrx8DZTJSNJpLkMZrxlXF2vdeao4CCBiXUtKBuxR7Nj2CQIBy3L3bSB
    repo: nfsim
    package: nfsim
    version: 1.0
    artifact: nfsim
    publish: true
    override: true
